[package]
name = "text-editor"
version = "0.1.0"
edition = "2021"
authors = ["Ceferino Patino <c4patino@gmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
crossterm = "0.28.1"
